id: P004342
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD89051
  title: བཀའ་གདམས་གསུང་འབུམ་ཕྱོགས་བསྒྲིགས་ཐེངས་དང་པོ།
  author: ''
  volumes:
    89c3f1892a544fff955ef5591821fb13:
      image_group_id: I1PD89053
      title: ''
      volume_number: 1
      total_pages: 716
      base_file: v001.txt
    1cf4551f25294db09926053ea3919c7e:
      image_group_id: I1PD89054
      title: ''
      volume_number: 2
      total_pages: 454
      base_file: v002.txt
    3b1161af7bc34d4ea9910c77a184ace2:
      image_group_id: I1PD89055
      title: ''
      volume_number: 3
      total_pages: 752
      base_file: v003.txt
    c5994dcceb4f4bafb483b68ab9d9f7d3:
      image_group_id: I1PD89056
      title: ''
      volume_number: 4
      total_pages: 742
      base_file: v004.txt
    c153ac450aec44a0bcd008d4aec6806c:
      image_group_id: I1PD89057
      title: ''
      volume_number: 5
      total_pages: 608
      base_file: v005.txt
    04598a4de95a4f8eb373263b49022b83:
      image_group_id: I1PD89058
      title: ''
      volume_number: 6
      total_pages: 524
      base_file: v006.txt
    0a748e7182a14ef78c8967fedb7c80fc:
      image_group_id: I1PD89059
      title: ''
      volume_number: 7
      total_pages: 578
      base_file: v007.txt
    b6f2647c021743e2ae896298b50629c1:
      image_group_id: I1PD89060
      title: ''
      volume_number: 8
      total_pages: 634
      base_file: v008.txt
    538def5280ca4526a15449a0c0901cf3:
      image_group_id: I1PD89061
      title: ''
      volume_number: 9
      total_pages: 604
      base_file: v009.txt
    6f3b9b9c5afa4428b4cd5d822acfbd2b:
      image_group_id: I1PD89062
      title: ''
      volume_number: 10
      total_pages: 664
      base_file: v010.txt
    98bdbcb556274be485db6f3900b19363:
      image_group_id: I1PD89063
      title: ''
      volume_number: 11
      total_pages: 632
      base_file: v011.txt
    fb51b33d7acd4d759debec73ae6d242d:
      image_group_id: I1PD89064
      title: ''
      volume_number: 12
      total_pages: 514
      base_file: v012.txt
    d2ef713aeecd41eb9696165eae1c3c67:
      image_group_id: I1PD89065
      title: ''
      volume_number: 13
      total_pages: 826
      base_file: v013.txt
    75b194422d3a41d3b575b05e22823303:
      image_group_id: I1PD89066
      title: ''
      volume_number: 14
      total_pages: 608
      base_file: v014.txt
    fbd517b93b434305be298ccb9530cd06:
      image_group_id: I1PD89067
      title: ''
      volume_number: 15
      total_pages: 660
      base_file: v015.txt
    0c1aa4eb5edc48bfbb9d7a4ef563f60a:
      image_group_id: I1PD89068
      title: ''
      volume_number: 16
      total_pages: 624
      base_file: v016.txt
    b35622f4e883435296e79c6d74c4cd99:
      image_group_id: I1PD89069
      title: ''
      volume_number: 17
      total_pages: 698
      base_file: v017.txt
    27604ed47556494b89497b8efdc3ad12:
      image_group_id: I1PD89070
      title: ''
      volume_number: 18
      total_pages: 504
      base_file: v018.txt
    64625b2016ea4976a219a05e9aa3051e:
      image_group_id: I1PD89071
      title: ''
      volume_number: 19
      total_pages: 692
      base_file: v019.txt
    5a2249c8e33c46b893eab7e8542a6b4d:
      image_group_id: I1PD89072
      title: ''
      volume_number: 20
      total_pages: 574
      base_file: v020.txt
    bd51156458e34314b3b754a19b5c8a4e:
      image_group_id: I1PD89073
      title: ''
      volume_number: 21
      total_pages: 632
      base_file: v021.txt
    bddb5d89facc44eda8364110ed9a0659:
      image_group_id: I1PD89074
      title: ''
      volume_number: 22
      total_pages: 538
      base_file: v022.txt
    141f76136aa24afdb359c67f223f06f8:
      image_group_id: I1PD89075
      title: ''
      volume_number: 23
      total_pages: 608
      base_file: v023.txt
    0eba42e3598d477393a6f6034e98f448:
      image_group_id: I1PD89076
      title: ''
      volume_number: 24
      total_pages: 532
      base_file: v024.txt
    098a47ba663f4c27babbe08c2f71d18f:
      image_group_id: I1PD89077
      title: ''
      volume_number: 25
      total_pages: 660
      base_file: v025.txt
    f0c854e7d41e4e76b63f4bf4d98efc72:
      image_group_id: I1PD89078
      title: ''
      volume_number: 26
      total_pages: 544
      base_file: v026.txt
    f250e6e59bef420bbeb3cf1a6ea86861:
      image_group_id: I1PD89079
      title: ''
      volume_number: 27
      total_pages: 630
      base_file: v027.txt
    11d688daac7944048065d1cf382e4e0b:
      image_group_id: I1PD89080
      title: ''
      volume_number: 28
      total_pages: 642
      base_file: v028.txt
    fce7cae4b71a44dd8a15b991252fbc61:
      image_group_id: I1PD89081
      title: ''
      volume_number: 29
      total_pages: 512
      base_file: v029.txt
    3dfb4fd9478b488ebab038425b80e732:
      image_group_id: I1PD89082
      title: ''
      volume_number: 30
      total_pages: 480
      base_file: v030.txt
    be6b451eacf54266b1d5e41f879e1020:
      image_group_id: I1PD89083
      title: ''
      volume_number: 31
      total_pages: 231
      base_file: v031.txt
